/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PayLock {
  export type ItemStruct = {
    id: BigNumberish;
    seller: AddressLike;
    name: string;
    ipfsCid: string;
    previewCid: string;
    fileType: string;
    price: BigNumberish;
    buyer: AddressLike;
    encryptedKey: string;
    isSold: boolean;
    isKeyDelivered: boolean;
    listedAt: BigNumberish;
    soldAt: BigNumberish;
  };

  export type ItemStructOutput = [
    id: bigint,
    seller: string,
    name: string,
    ipfsCid: string,
    previewCid: string,
    fileType: string,
    price: bigint,
    buyer: string,
    encryptedKey: string,
    isSold: boolean,
    isKeyDelivered: boolean,
    listedAt: bigint,
    soldAt: bigint
  ] & {
    id: bigint;
    seller: string;
    name: string;
    ipfsCid: string;
    previewCid: string;
    fileType: string;
    price: bigint;
    buyer: string;
    encryptedKey: string;
    isSold: boolean;
    isKeyDelivered: boolean;
    listedAt: bigint;
    soldAt: bigint;
  };
}

export interface PayLockInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buyItem"
      | "deliverKey"
      | "getItem"
      | "getMarketplaceItems"
      | "items"
      | "listItem"
      | "owner"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ItemListed"
      | "ItemPurchased"
      | "KeyDelivered"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "buyItem",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deliverKey",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getItem",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketplaceItems",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "items", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "listItem",
    values: [string, string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "buyItem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deliverKey", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getItem", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMarketplaceItems",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "items", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "listItem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ItemListedEvent {
  export type InputTuple = [
    id: BigNumberish,
    seller: AddressLike,
    price: BigNumberish,
    name: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    seller: string,
    price: bigint,
    name: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    id: bigint;
    seller: string;
    price: bigint;
    name: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ItemPurchasedEvent {
  export type InputTuple = [
    id: BigNumberish,
    buyer: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [id: bigint, buyer: string, timestamp: bigint];
  export interface OutputObject {
    id: bigint;
    buyer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KeyDeliveredEvent {
  export type InputTuple = [
    id: BigNumberish,
    encryptedKey: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    encryptedKey: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    id: bigint;
    encryptedKey: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PayLock extends BaseContract {
  connect(runner?: ContractRunner | null): PayLock;
  waitForDeployment(): Promise<this>;

  interface: PayLockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyItem: TypedContractMethod<[_id: BigNumberish], [void], "payable">;

  deliverKey: TypedContractMethod<
    [_id: BigNumberish, _keyForBuyer: string],
    [void],
    "nonpayable"
  >;

  getItem: TypedContractMethod<
    [_id: BigNumberish],
    [PayLock.ItemStructOutput],
    "view"
  >;

  getMarketplaceItems: TypedContractMethod<
    [],
    [PayLock.ItemStructOutput[]],
    "view"
  >;

  items: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        bigint,
        string,
        string,
        boolean,
        boolean,
        bigint,
        bigint
      ] & {
        id: bigint;
        seller: string;
        name: string;
        ipfsCid: string;
        previewCid: string;
        fileType: string;
        price: bigint;
        buyer: string;
        encryptedKey: string;
        isSold: boolean;
        isKeyDelivered: boolean;
        listedAt: bigint;
        soldAt: bigint;
      }
    ],
    "view"
  >;

  listItem: TypedContractMethod<
    [
      _name: string,
      _ipfsCid: string,
      _previewCid: string,
      _fileType: string,
      _price: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyItem"
  ): TypedContractMethod<[_id: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "deliverKey"
  ): TypedContractMethod<
    [_id: BigNumberish, _keyForBuyer: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getItem"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [PayLock.ItemStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMarketplaceItems"
  ): TypedContractMethod<[], [PayLock.ItemStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "items"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        bigint,
        string,
        string,
        boolean,
        boolean,
        bigint,
        bigint
      ] & {
        id: bigint;
        seller: string;
        name: string;
        ipfsCid: string;
        previewCid: string;
        fileType: string;
        price: bigint;
        buyer: string;
        encryptedKey: string;
        isSold: boolean;
        isKeyDelivered: boolean;
        listedAt: bigint;
        soldAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "listItem"
  ): TypedContractMethod<
    [
      _name: string,
      _ipfsCid: string,
      _previewCid: string,
      _fileType: string,
      _price: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ItemListed"
  ): TypedContractEvent<
    ItemListedEvent.InputTuple,
    ItemListedEvent.OutputTuple,
    ItemListedEvent.OutputObject
  >;
  getEvent(
    key: "ItemPurchased"
  ): TypedContractEvent<
    ItemPurchasedEvent.InputTuple,
    ItemPurchasedEvent.OutputTuple,
    ItemPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "KeyDelivered"
  ): TypedContractEvent<
    KeyDeliveredEvent.InputTuple,
    KeyDeliveredEvent.OutputTuple,
    KeyDeliveredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "ItemListed(uint256,address,uint256,string,uint256)": TypedContractEvent<
      ItemListedEvent.InputTuple,
      ItemListedEvent.OutputTuple,
      ItemListedEvent.OutputObject
    >;
    ItemListed: TypedContractEvent<
      ItemListedEvent.InputTuple,
      ItemListedEvent.OutputTuple,
      ItemListedEvent.OutputObject
    >;

    "ItemPurchased(uint256,address,uint256)": TypedContractEvent<
      ItemPurchasedEvent.InputTuple,
      ItemPurchasedEvent.OutputTuple,
      ItemPurchasedEvent.OutputObject
    >;
    ItemPurchased: TypedContractEvent<
      ItemPurchasedEvent.InputTuple,
      ItemPurchasedEvent.OutputTuple,
      ItemPurchasedEvent.OutputObject
    >;

    "KeyDelivered(uint256,string,uint256)": TypedContractEvent<
      KeyDeliveredEvent.InputTuple,
      KeyDeliveredEvent.OutputTuple,
      KeyDeliveredEvent.OutputObject
    >;
    KeyDelivered: TypedContractEvent<
      KeyDeliveredEvent.InputTuple,
      KeyDeliveredEvent.OutputTuple,
      KeyDeliveredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
