/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PayLock {
  export type ItemStruct = {
    id: BigNumberish;
    seller: AddressLike;
    name: string;
    ipfsCid: string;
    previewCid: string;
    fileType: string;
    price: BigNumberish;
    maxSupply: BigNumberish;
    soldCount: BigNumberish;
    isSoldOut: boolean;
  };

  export type ItemStructOutput = [
    id: bigint,
    seller: string,
    name: string,
    ipfsCid: string,
    previewCid: string,
    fileType: string,
    price: bigint,
    maxSupply: bigint,
    soldCount: bigint,
    isSoldOut: boolean
  ] & {
    id: bigint;
    seller: string;
    name: string;
    ipfsCid: string;
    previewCid: string;
    fileType: string;
    price: bigint;
    maxSupply: bigint;
    soldCount: bigint;
    isSoldOut: boolean;
  };
}

export interface PayLockInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buyItem"
      | "buyerKeys"
      | "cancelListing"
      | "checkOwnership"
      | "deliverKey"
      | "getMarketplaceItems"
      | "hasBought"
      | "itemCount"
      | "items"
      | "listItem"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ItemCanceled"
      | "ItemListed"
      | "ItemPurchased"
      | "KeyDelivered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "buyItem",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyerKeys",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelListing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkOwnership",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deliverKey",
    values: [BigNumberish, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketplaceItems",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasBought",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "itemCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "items", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "listItem",
    values: [string, string, string, string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "buyItem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyerKeys", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deliverKey", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMarketplaceItems",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasBought", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "itemCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "items", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "listItem", data: BytesLike): Result;
}

export namespace ItemCanceledEvent {
  export type InputTuple = [id: BigNumberish, seller: AddressLike];
  export type OutputTuple = [id: bigint, seller: string];
  export interface OutputObject {
    id: bigint;
    seller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ItemListedEvent {
  export type InputTuple = [
    id: BigNumberish,
    seller: AddressLike,
    price: BigNumberish,
    name: string,
    maxSupply: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    seller: string,
    price: bigint,
    name: string,
    maxSupply: bigint
  ];
  export interface OutputObject {
    id: bigint;
    seller: string;
    price: bigint;
    name: string;
    maxSupply: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ItemPurchasedEvent {
  export type InputTuple = [id: BigNumberish, buyer: AddressLike];
  export type OutputTuple = [id: bigint, buyer: string];
  export interface OutputObject {
    id: bigint;
    buyer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KeyDeliveredEvent {
  export type InputTuple = [
    id: BigNumberish,
    buyer: AddressLike,
    encryptedKey: string
  ];
  export type OutputTuple = [id: bigint, buyer: string, encryptedKey: string];
  export interface OutputObject {
    id: bigint;
    buyer: string;
    encryptedKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PayLock extends BaseContract {
  connect(runner?: ContractRunner | null): PayLock;
  waitForDeployment(): Promise<this>;

  interface: PayLockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyItem: TypedContractMethod<[_id: BigNumberish], [void], "payable">;

  buyerKeys: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [string],
    "view"
  >;

  cancelListing: TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;

  checkOwnership: TypedContractMethod<
    [_id: BigNumberish, _user: AddressLike],
    [[boolean, string] & { bought: boolean; key: string }],
    "view"
  >;

  deliverKey: TypedContractMethod<
    [_id: BigNumberish, _buyer: AddressLike, _keyForBuyer: string],
    [void],
    "nonpayable"
  >;

  getMarketplaceItems: TypedContractMethod<
    [],
    [PayLock.ItemStructOutput[]],
    "view"
  >;

  hasBought: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  itemCount: TypedContractMethod<[], [bigint], "view">;

  items: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        id: bigint;
        seller: string;
        name: string;
        ipfsCid: string;
        previewCid: string;
        fileType: string;
        price: bigint;
        maxSupply: bigint;
        soldCount: bigint;
        isSoldOut: boolean;
      }
    ],
    "view"
  >;

  listItem: TypedContractMethod<
    [
      _name: string,
      _ipfsCid: string,
      _previewCid: string,
      _fileType: string,
      _price: BigNumberish,
      _maxSupply: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyItem"
  ): TypedContractMethod<[_id: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "buyerKeys"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelListing"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkOwnership"
  ): TypedContractMethod<
    [_id: BigNumberish, _user: AddressLike],
    [[boolean, string] & { bought: boolean; key: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "deliverKey"
  ): TypedContractMethod<
    [_id: BigNumberish, _buyer: AddressLike, _keyForBuyer: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getMarketplaceItems"
  ): TypedContractMethod<[], [PayLock.ItemStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "hasBought"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "itemCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "items"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        id: bigint;
        seller: string;
        name: string;
        ipfsCid: string;
        previewCid: string;
        fileType: string;
        price: bigint;
        maxSupply: bigint;
        soldCount: bigint;
        isSoldOut: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "listItem"
  ): TypedContractMethod<
    [
      _name: string,
      _ipfsCid: string,
      _previewCid: string,
      _fileType: string,
      _price: BigNumberish,
      _maxSupply: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ItemCanceled"
  ): TypedContractEvent<
    ItemCanceledEvent.InputTuple,
    ItemCanceledEvent.OutputTuple,
    ItemCanceledEvent.OutputObject
  >;
  getEvent(
    key: "ItemListed"
  ): TypedContractEvent<
    ItemListedEvent.InputTuple,
    ItemListedEvent.OutputTuple,
    ItemListedEvent.OutputObject
  >;
  getEvent(
    key: "ItemPurchased"
  ): TypedContractEvent<
    ItemPurchasedEvent.InputTuple,
    ItemPurchasedEvent.OutputTuple,
    ItemPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "KeyDelivered"
  ): TypedContractEvent<
    KeyDeliveredEvent.InputTuple,
    KeyDeliveredEvent.OutputTuple,
    KeyDeliveredEvent.OutputObject
  >;

  filters: {
    "ItemCanceled(uint256,address)": TypedContractEvent<
      ItemCanceledEvent.InputTuple,
      ItemCanceledEvent.OutputTuple,
      ItemCanceledEvent.OutputObject
    >;
    ItemCanceled: TypedContractEvent<
      ItemCanceledEvent.InputTuple,
      ItemCanceledEvent.OutputTuple,
      ItemCanceledEvent.OutputObject
    >;

    "ItemListed(uint256,address,uint256,string,uint256)": TypedContractEvent<
      ItemListedEvent.InputTuple,
      ItemListedEvent.OutputTuple,
      ItemListedEvent.OutputObject
    >;
    ItemListed: TypedContractEvent<
      ItemListedEvent.InputTuple,
      ItemListedEvent.OutputTuple,
      ItemListedEvent.OutputObject
    >;

    "ItemPurchased(uint256,address)": TypedContractEvent<
      ItemPurchasedEvent.InputTuple,
      ItemPurchasedEvent.OutputTuple,
      ItemPurchasedEvent.OutputObject
    >;
    ItemPurchased: TypedContractEvent<
      ItemPurchasedEvent.InputTuple,
      ItemPurchasedEvent.OutputTuple,
      ItemPurchasedEvent.OutputObject
    >;

    "KeyDelivered(uint256,address,string)": TypedContractEvent<
      KeyDeliveredEvent.InputTuple,
      KeyDeliveredEvent.OutputTuple,
      KeyDeliveredEvent.OutputObject
    >;
    KeyDelivered: TypedContractEvent<
      KeyDeliveredEvent.InputTuple,
      KeyDeliveredEvent.OutputTuple,
      KeyDeliveredEvent.OutputObject
    >;
  };
}
